spring:
  datasource:
    presto-gateway:
      jdbc-url: jdbc:mysql://localhost:3306/presto_gateway?serverTimezone=Asia/Shanghai
      username: root
      password: 1111
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9200

presto-gateway:
  sdfTimeZoneId: GMT-6

kafka:
  enabled: true
  topic: presto-query
  bootstrapServers: mq1:9200,mq2:9200,mq3:9200

